### ISSUE TITLE
Structure the todo app

### ISSUE THREAD

**Issue by Prakhargarg-2010196** [Prakhargarg-2010196/Todo_VanillaJS#2]
- [x] Explore todo apps 
- [x] Design Todo app 
- [x] How to structure html app.
  - [x] Semantic tags 
  - [x] MVC architechture
- [x] Structure todo app according to the concepts learnt
- [x] Draw on excalidraw a raw structure 
- [x] Implement the structure in html
